import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useNavigate, useSearchParams } from 'react-router-dom';
import './styles.css';

const Logo = () => <div className="logo"><i>✦</i> RESQ AI</div>;
const Metric = ({ label, value, hint, warn }) => <article className="metric"><small>{label}</small><b>{value}</b><span className={warn ? 'warn' : ''}>{hint}</span></article>;
const Event = ({ icon, title, text, time, green }) => <article className="event"><i className={green ? 'green' : ''}>{icon}</i><div><b>{title}</b><p>{text}</p></div><time>{time}</time></article>;

function Home() {
  const hour = new Date().getHours();
  const salutation = hour < 12 ? 'morning' : hour < 17 ? 'afternoon' : 'evening';
  return <div className="page"><header><Logo/><div className="header-right"><span className="health"><i/> Systems operational</span><span className="clock">01 AUG 2026 · 10:30 IST</span><Link to="/login" className="signin">Sign in</Link><Link to="/login?mode=signup" className="signup">Sign up</Link></div></header><main className="dashboard"><section className="hero"><div className="eyebrow">Emergency intelligence system</div><h1>Welcome, good {salutation}.</h1><p>A unified view of live signals, affected regions, and response priorities—so every decision reaches the people who need it most.</p><button>Open live operations →</button><a href="#brief">View incident brief</a></section><section className="map"><div><b>Live risk overview</b><span>Southern India · multi-source analysis</span></div><div className="map-grid"/><span className="hotspot one"/><span className="hotspot two"/><span className="hotspot three"/><small>● 18 active data feeds</small></section><div className="section-head"><h2>Situation at a glance</h2><a>Full analytics →</a></div><section className="metrics"><Metric label="ACTIVE INCIDENTS" value="12" hint="↑ 3 since yesterday"/><Metric label="PEOPLE AT RISK" value="24.8k" hint="↑ 8.4% projected" warn/><Metric label="RESPONSE UNITS" value="86" hint="72 currently deployed"/><Metric label="DATA CONFIDENCE" value="94%" hint="Across 18 live sources"/></section><section className="feed"><h2>Live intelligence feed</h2><Event icon="▲" title="Flood extent increased near Kottayam" text="Satellite scan confirms 3 new inundated zones." time="4 MIN"/><Event icon="◎" title="Medical unit dispatched to Sector 07" text="Estimated arrival time: 16 minutes." time="11 MIN" green/><Event icon="≋" title="Heavy rainfall alert issued" text="Forecast indicates severe precipitation in next 6 hours." time="18 MIN"/></section><section className="priorities"><div className="priority-title"><div><h2>Response priorities</h2><span>AI-ranked by urgency and access</span></div><em>LIVE</em></div><Priority title="Changanassery West" info="Flooding · 6,240 people exposed" risk="CRITICAL"/><Priority title="Vagamon Valley" info="Landslide risk · 3 routes blocked" risk="CRITICAL"/><Priority title="Alappuzha Coast" info="Storm surge · 4 shelters on standby" risk="ELEVATED" medium/></section><footer>ALL INSIGHTS ARE CONTINUOUSLY SYNTHESIZED FROM WEATHER, SATELLITE, DRONE &amp; FIELD REPORTS.</footer></main></div>;
}
function Priority({ title, info, risk, medium }) { return <div className="priority"><div><b>{title}</b><span>{info}</span></div><strong className={medium ? 'medium' : ''}>{risk}</strong></div>; }
function Login() {
  const [params] = useSearchParams(); const [signup, setSignup] = useState(params.get('mode') === 'signup'); const nav = useNavigate();
  const submit = e => { e.preventDefault(); nav('/'); };
  return <div className="auth-page"><div className="auth-card"><section className="auth-copy"><Logo/><div><div className="eyebrow">Emergency intelligence</div><h1>Ready when every second matters.</h1><p>Secure access to live operational insight, coordinated response priorities, and critical field intelligence.</p></div></section><section className="form"><Link to="/" className="back">← Back to overview</Link><h2>{signup ? 'Create your account' : 'Welcome back'}</h2><p>{signup ? 'Start your secure ResQ AI workspace.' : 'Sign in to access your operations workspace.'}</p><form onSubmit={submit}><label>WORK EMAIL</label><input type="email" placeholder="name@organization.org" required/>{signup && <><label>ORGANIZATION</label><input placeholder="Organization name" required/></>}<label>PASSWORD</label><input type="password" placeholder="Enter your password" required/><div className="form-actions"><label className="check"><input type="checkbox"/> Keep me signed in</label>{!signup && <a href="#forgot">Forgot password?</a>}</div><button type="submit">{signup ? 'Create account →' : 'Sign in to ResQ AI →'}</button></form><div className="or">OR CONTINUE WITH</div><button className="sso">⌘ &nbsp; Sign in with organization SSO</button><p className="switch">{signup ? 'Already have an account?' : 'New to ResQ AI?'} <button onClick={() => setSignup(!signup)}>{signup ? 'Sign in' : 'Create an account'}</button></p></section></div></div>;
}
function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/></Routes>; }
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
